### ISSUE TITLE
couldn't run example game

### ISSUE THREAD

**Issue by TST314** [RobLoach/node-raylib#39]
I have CMake installed but the example won't run. I get this error when I type :
 bin/node-raylib.exe templates/simple_game/simple_game.js S

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! raylib@0.1.1 postinstall: `cmake-js compile`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the raylib@0.1.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Shreyas\AppData\Roaming\npm-cache\_logs\2019-07-29T22_14_29_326Z-debug.log
PS C:\Users\Shreyas\3D Objects\node-raylib-master\templates\simple_game> bin/node-raylib.exe templates/simple_game.js

**Comment by RobLoach** [comment]
Hmm, I've just pushed a 0.2.0 update. And it seemed to have built okay for me. Which version of node are you on?

**Comment by TST314** [comment]
v8.12.0 which I believe is not the current version now that I check it. Would that be the problem?

**Comment by RobLoach** [comment]
Quite possibly, yes. I think node-raylib needs at least Node.js 10.

**Comment by TST314** [comment]
with Node.js v12.7 I still get an error.  This is what I get from when it
begins to say error. I got this after typing npm install.


CMake Error at CMakeLists.txt:2 (project):
  Generator

    Visual Studio 15 2017 Win64

  could not find any instance of Visual Studio.



-- Configuring incomplete, errors occurred!
See also "C:/Users/Shreyas/3D
Objects/node-raylib-master/templates/simple_game/node_modules/raylib/build/CMakeFiles/CMakeOutput.log".
ERR! OMG Process terminated: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! raylib@0.2.0 postinstall: `cmake-js compile`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the raylib@0.2.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely
additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!
C:\Users\Shreyas\AppData\Roaming\npm-cache\_logs\2019-07-31T23_45_17_726Z-debug.log
PS C:\Users\Shreyas\3D Objects\node-raylib-master\templates\simple_game>

**Comment by HastagGuigui** [comment]
As I understood (I may be wrong), you need to install cmake-js ([`npm i cmake-js`](https://www.npmjs.com/package/cmake-js))
